# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23d8f190bd061e6dc76d59ba601066bad067d0efe653ac0e41d721bc26f3f8a387c8f7d3f28184dfb3f5520e0e536e874560efcc1286f7c016f35169c7e96b08

test:
  secret_key_base: e14652b8e34922af1d671a2bff62eedae81266d6258a53f281a7fabdb642e9513d8a635a12eab71641c658d4704bc1fe2c40473d39dd13463a62607a23c8f70e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
